# GitHub action checking the code quality
name: Angular application

# Run this workflow on every commit
on: [push]

# Execute this worflow on every commit
jobs:
    # Linting application
    lint:
        name: Angular linting
        runs-on: ubuntu-latest

        steps:
            - name: Checkout module
              uses: actions/checkout@v2

            - name: Set up NPM
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Install angular
              run: |
                sudo npm install -g @angular/cli
                npm install

            - name: Run linting
              run: ng lint

    # Running tests
    tests:
        name: Angular tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout module
              uses: actions/checkout@v2

            - name: Set up NPM
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Install angular
              run: |
                sudo npm install -g @angular/cli
                npm install

            - name: Run tests
              run: ng test --watch=false --code-coverage --browsers=ChromeHeadless

            - name: Covarage report
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: coverage/roulette
                if-no-files-found: error
                retention-days: 30
                overwrite: true

    # Build application
    build:
        name: Build angular application
        runs-on: ubuntu-latest

        steps:
            - name: Checkout module
              uses: actions/checkout@v2

            - name: Set up NPM
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Install angular
              run: |
                sudo npm install -g @angular/cli
                npm install

            - name: Compile
              run: ng build --configuration production

            - name: Angular application
              uses: actions/upload-artifact@v4
              with:
                name: github-pages
                path: dist/roulette/browser
                if-no-files-found: error
                retention-days: 30
                overwrite: true

    # Deploy
    deploy:
        name: Deploy angular application
        runs-on: ubuntu-latest
        needs: [lint, tests, build]

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy site
              uses: actions/deploy-pages@v4
              id: deployment
              with:
                artifact_name: github-pages
